### ISSUE TITLE
Does it work with Python 3.x?

### ISSUE THREAD

**Issue by garethjax** [c0decracker/video-splitter#11]
I'm getting some errors like:

> print "Format not supported. File must be a csv or json file"
>                                                                 ^
> SyntaxError: Missing parentheses in call to 'print'

**Comment by fishnal** [comment]
Judging by the way the print statement is written, I'd assume that it's for Python 2.

**Comment by c0decracker** [comment]
@fishnal Is right, this was built for Python 2.x. It probably wouldn't be too difficult to adapt it to Python 3 though.

**Comment by fishnal** [comment]
@c0decracker would syntax be the main issue for porting it to py3?

**Comment by c0decracker** [comment]
Yes @fishnal , I believe all the modules it uses present in py3 as well.

**Comment by lucas-in-china** [comment]
I got this to work for with py3 just by updating the print statements to include parenthesis.
