### ISSUE TITLE
Video is blank for few seconds in the beginning

### ISSUE THREAD

**Issue by ShridharBhatGokarna** [c0decracker/video-splitter#16]
Hi All,

I am using this utility to split videos. I am able to split the videos , however the first few seconds of the video are blank for some reason. Can you please help me out.

Thanks and Regards,
Shridhar

**Comment by AlexanderKozhevin** [comment]
Yeah, it's some big problem with ffmpeg. 
I tested different options. And sometimes it has blank screen in the beginning. 
But in other options it produces extra second at the end with frozen video.

**Comment by AlexanderKozhevin** [comment]
I guess it's just not possible to make it other way because of video compression. 
I used opencv-python to process video frame by frame.

**Comment by taylorjdawson** [comment]
@AlexanderKozhevin @shahinism Please see #9 
adding this,`-v libx264 `, should fix the issue

**Comment by c0decracker** [comment]
Thanks @taylorjdawson !
