### ISSUE TITLE
Batch Split

### ISSUE THREAD

**Issue by manujchandra** [c0decracker/video-splitter#18]
Hi, is there any option to split all videos in a folder?

Thanks.

**Comment by c0decracker** [comment]
You can do it with some command line foo and xargs, for example:
`ls -1 ./testbed/Mp4/*.mp4 | xargs -I {} python ffmpeg-split.py -f {} -c 2`

Here ./testbed/Mp4 is where multiple videos (in format .mp4) are placed, so it feeds them one by one to ffmpeg-split.py to split into 2 chunks (the -c 2 part). Hope this helps.
