### ISSUE TITLE
Split into truly equal size

### ISSUE THREAD

**Issue by wordlessly** [c0decracker/video-splitter#19]
Hi,

Example: video of 39 minute length. I want to split it into equal sizes. Each size should not exceed 15 minutes.

Traditionally with -s 900 I would get three parts: 15min, 15min, 9min. I want however three parts of equal length which would be 13min. Obviously I could fetch a calculator and type in the seconds I want. Still the script could do this automagically :)

**Comment by shafcodes** [comment]
Thought:
You could ffprobe the duration, convert it to seconds, and divide it by 3 and pass it to the script.

**Comment by c0decracker** [comment]
That is now (for a while I should say) possible with -c command line argument. Thanks @csabahenk for adding that a while ago.
