### ISSUE TITLE
Problem running program - print statements being funky

### ISSUE THREAD

**Issue by picklezA** [c0decracker/video-splitter#21]
I'm using python 3.8 on windows 10 and I went to open the help prompt in cmd and the program kept giving me error codes, so I had to manually edit all the print statements and added back the () so it would run. I'm not sure why it messed up but it did. The attached file is the print statement edited properly ig

[ffmpeg-split.txt](https://github.com/c0decracker/video-splitter/files/4678500/ffmpeg-split.txt)

hope this helps

**Comment by c0decracker** [comment]
Thank you! One of those days I"ll get to updating this in the code :)

**Comment by c0decracker** [comment]
@picklezA with the latest update Python 3.x should be supported OK. I've tested it on 3.9, but not on Windows (don't have one around unfortunately).
