### ISSUE TITLE
Add support for multi-stream videos

### ISSUE THREAD

**Issue by junaidmgithub** [c0decracker/video-splitter#26]
While Splitting video having more than one audio stream, the output videos contain only 1 audio stream.

ffmpeg default stream selection will not automatically choose all of the streams from video
Using the '-map' option disables the default stream selection behavior and allows you to manually choose streams.

Adding -map 0 in command will select all streams from input video

reference: https://trac.ffmpeg.org/wiki/Map

**Comment by c0decracker** [comment]
@junaidmgithub So basically you want to be able to specify stream exactly same way that ffmpeg has it?

**Comment by c0decracker** [comment]
If this solution won't work -- please let me know / reopen this issue!
