### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by wreckzone007** [c0decracker/video-splitter#27]
I've followed the steps and this error message shows up

**Comment by c0decracker** [comment]
How did you invoke the script via CLI exactly (what were the parameters)?

**Comment by c0decracker** [comment]
Closing since no additional info provided. Please reopen if still an issue.

**Comment by sarkarghya** [comment]
Hey there I'm getting similar errors
I'm using python to be precise ``` Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:34:34) [MSC v.1928 32 bit (Intel)] on win32 ```
I am using the windows terminal. I ```cd```ed into my directory and I ran the file on my python environment using ``` & "C:/Program Files/Python38-32/python.exe" ffmpeg-split.py -f xp.mp4 -s 1800 ``` which is same as ```python ffmpeg-split.py -f xp.mp4 -s 1800 ``` on the terminal.
I got a similar error. I tried providing the absolute path to my file using ```& "C:/Program Files/Python38-32/python.exe" ffmpeg-split.py -f "E://ds//AARM-018//xp.mp4" -s 1800```  but still got same error.

The exact log is as follows:
```
Traceback (most recent call last):
  File "ffmpeg-split.py", line 225, in <module>
    main()
  File "ffmpeg-split.py", line 221, in main
    split_by_seconds(video_length=video_length, **options.__dict__)
  File "ffmpeg-split.py", line 97, in split_by_seconds
    video_length = get_video_length(filename)
  File "ffmpeg-split.py", line 78, in get_video_length
    output = subprocess.check_output(("ffprobe", "-v", "error", "-show_entries", "format=duration", "-of",
  File "C:\Program Files\Python38-32\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\Python38-32\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python38-32\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python38-32\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

So I looked closely around line 78 
```
def get_video_length(filename):
    output = subprocess.check_output(("ffprobe", "-v", "error", "-show_entries", "format=duration", "-of",
                                      "default=noprint_wrappers=1:nokey=1", filename)).strip()
```
Since I was running things on terminal, I tried setting `shell=True` as an end attribute just like:
```
def get_video_length(filename):
    output = subprocess.check_output(("ffprobe", "-v", "error", "-show_entries", "format=duration", "-of",
                                      "default=noprint_wrappers=1:nokey=1", filename), shell=True).strip()
```
This is when I get this `subprocess.CalledProcessError: Command '('ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'default=noprint_wrappers=1:nokey=1', 'E://ds//AARM-018//xp.mp4')' returned non-zero exit status 1.`

Then I realized I messed things up for the worse.  Any ideas regarding my issue will be appreciated!
