### ISSUE TITLE
Split into equal file sizes

### ISSUE THREAD

**Issue by luisvalenzuelar** [c0decracker/video-splitter#30]
Hi there,

I split file into equal duration but file sizes are different. I need them to be equal sizes (for uploading restrictions). It does not seem to be possible as yet. Any easy way to implement it?

**Comment by c0decracker** [comment]
Yes there is -S option for that, for example like this to split video into files under 1 megabyte:

`python ffmpeg-split.py -f video.mp4 -S 1048576`
