### ISSUE TITLE
https://github.com/c0decracker/video-splitter

### ISSUE THREAD

**Issue by gufur** [c0decracker/video-splitter#5]
Tried to run 
python ffmpeg-split.py -f Myvideo.mp4 -m manifest.gun
got 
 File "ffmpeg-split.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
Is this a python release problem or ?
Gunnar
Hmmm some text did not show above. Lets see if this works

` File "ffmpeg-split.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
`

**Comment by c0decracker** [comment]
Looks like your ffmpeg-split.py is corrupted. Can you re-download it/clone it again?
