### ISSUE TITLE
First first seconds of split videos are blank

### ISSUE THREAD

**Issue by luismqueral** [c0decracker/video-splitter#9]
Thanks for this script! Very well done.

I'm noticing that when I run it, the resulting files begin with a few seconds of white (though the audio is intact). I'm wondering if you came across it all all on your end. Possibly a codec issue?

**Comment by luismqueral** [comment]
Heh, well looks like I just figured it out. For anyone that runs into this, throw a vcodec argument in there, like so:

`python ffmpeg-split.py -f out.mp4 -v libx264 -s 30`

**Comment by c0decracker** [comment]
Thanks for the note @luismqueral !
